version: "3.9"
services:
  api:
    build: .
    image: ampyfin/val:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./out:/app/out:rw
    depends_on:
      - writer

  writer:
    image: ampyfin/val:latest
    command: >
      python main.py
      --adapters yfinance
      --strategies peter_lynch,psales_rev
      --tickers NVAX,CTMX,AAPL,MSFT,TSLA
      --continuous
      --interval 120
    env_file:
      - .env
    volumes:
      - ./out:/app/out:rw
