mode: console          # console | gui | broadcast
run: once              # once | continuous
adapters: ["alpaca","yfinance", "polygon", "fmp", "mock_local"]
strategies: ["peter_lynch", "psales_rev"]
tickers: [
  "AAOI",
  "AAPL",
  "ABBV",
  "ABCL",
  "ABNB",
  "ACAD",
  "ACHR",
  "ACIU",
  "ACLS",
  "ACRS",
  "ADBE",
  "ADI",
  "ADMA",
  "ADPT",
  "ADSK",
  "AEHR",
  "AES",
  "AEVA",
  "AGCO",
  "AGIO",
  "AI",
  "AKAM",
  "AKRO",
  "ALB",
  "ALGN",
  "ALKS",
  "ALNY",
  "ALT",
  "ALV",
  "AMAT",
  "AMBA",
  "AMD",
  "AMGN",
  "AMKR",
  "AMLX",
  "AMPX",
  "AMRC",
  "AMRN",
  "AMRX",
  "AMSC",
  "AMZN",
  "ANET",
  "APLS",
  "APLT",
  "APTV",
  "ARM",
  "ARRY",
  "ARVN",
  "ARWR",
  "ASML",
  "ASND",
  "ASTS",
  "ASYS",
  "ATEN",
  "ATOM",
  "ATRA",
  "ATRO",
  "AUPH",
  "AUR",
  "AVAV",
  "AVGO",
  "AVNT",
  "AVNW",
  "AVTR",
  "AXON",
  "AZN",
  "AZTA",
  "BA",
  "BABA",
  "BAX",
  "BBAI",
  "BCLI",
  "BCRX",
  "BCTX",
  "BE",
  "BEAM",
  "BFLY",
  "BHC",
  "BHVN",
  "BIIB",
  "BILL",
  "BIO",
  "BIOX",
  "BKSY",
  "BLFS",
  "BLNK",
  "BMRN",
  "BMY",
  "BNTX",
  "BRKR",
  "BSX",
  "BSY",
  "BTAI",
  "BWA",
  "BYSI",
  "CAMT",
  "CARR",
  "CAT",
  "CC",
  "CDNS",
  "CERS",
  "CEVA",
  "CF",
  "CFLT",
  "CGEM",
  "CGNX",
  "CHPT",
  "CHRS",
  "CI",
  "CIEN",
  "CLSK",
  "CMBM",
  "COGT",
  "COHR",
  "COHU",
  "COIN",
  "COST",
  "CRBP",
  "CRBU",
  "CRDO",
  "CRL",
  "CRM",
  "CRSP",
  "CRUS",
  "CRWD",
  "CSCO",
  "CTMX",
  "CTS",
  "CTVA",
  "CYBR",
  "CYTK",
  "DAKT",
  "DAN",
  "DASH",
  "DAWN",
  "DDD",
  "DDOG",
  "DE",
  "DELL",
  "DHR",
  "DIOD",
  "DNA",
  "DNLI",
  "DOCU",
  "DT",
  "DXCM",
  "DYN",
  "EA",
  "EDIT",
  "EH",
  "EMR",
  "ENLT",
  "ENPH",
  "ENTA",
  "ENTG",
  "ENVX",
  "EOSE",
  "EPAM",
  "ESTC",
  "ETN",
  "EVEX",
  "EVGO",
  "EW",
  "EWTX",
  "EXAS",
  "EXEL",
  "F",
  "FATE",
  "FLEX",
  "FLNC",
  "FMC",
  "FOLD",
  "FORM",
  "FSLR",
  "FSLY",
  "FTNT",
  "FTV",
  "GEHC",
  "GEV",
  "GFS",
  "GH",
  "GHRS",
  "GILD",
  "GLOB",
  "GLPG",
  "GLUE",
  "GLW",
  "GM",
  "GMED",
  "GOGO",
  "GOOG",
  "GOOGL",
  "GRMN",
  "GSAT",
  "GSIT",
  "GTLB",
  "GWH",
  "HAE",
  "HALO",
  "HASI",
  "HEI",
  "HIMX",
  "HOLX",
  "HOOD",
  "HOOK",
  "HPE",
  "HSIC",
  "HUBS",
  "HUM",
  "HWM",
  "HXL",
  "IBM",
  "ICLR",
  "IDXX",
  "ILMN",
  "IMAB",
  "IMCR",
  "IMMR",
  "IMOS",
  "IMVT",
  "INCY",
  "INMD",
  "INSG",
  "INSM",
  "INSP",
  "INTC",
  "INTU",
  "INVA",
  "INVZ",
  "IONS",
  "IOT",
  "IOVA",
  "IPGP",
  "IQV",
  "IRBT",
  "IRDM",
  "IRTC",
  "ISRG",
  "ITRI",
  "JBL",
  "JNJ",
  "JOBY",
  "KEYS",
  "KLAC",
  "KLIC",
  "KN",
  "KNSA",
  "KRYS",
  "KURA",
  "KYMR",
  "LAB",
  "LAC",
  "LASR",
  "LAZR",
  "LCID",
  "LEA",
  "LFUS",
  "LGND",
  "LI",
  "LITE",
  "LLY",
  "LMT",
  "LRCX",
  "LSCC",
  "LUMN",
  "LUNR",
  "MARA",
  "MASI",
  "MAXN",
  "MBLY",
  "MCHP",
  "MDB",
  "META",
  "MGA",
  "MKSI",
  "MLTX",
  "MMM",
  "MNDY",
  "MP",
  "MPWR",
  "MRAM",
  "MRCY",
  "MRK",
  "MRNA",
  "MRVL",
  "MSFT",
  "MTLS",
  "MTRN",
  "MTSI",
  "MU",
  "MXL",
  "NAUT",
  "NBIX",
  "NEE",
  "NET",
  "NIO",
  "NNDM",
  "NOC",
  "NXT",
  "NOW",
  "NRIX",
  "NTAP",
  "NTCT",
  "NTLA",
  "NTNX",
  "NTRA",
  "NVAX",
  "NVCR",
  "NVDA",
  "NVEC",
  "NVMI",
  "NVO",
  "NVS",
  "NVST",
  "NVTS",
  "NXPI",
  "OGN",
  "OKTA",
  "OLED",
  "OLMA",
  "OMCL",
  "ON",
  "ONTO",
  "ORA",
  "ORCL",
  "OUST",
  "PACB",
  "PANW",
  "PATH",
  "PBYI",
  "PDSB",
  "PEN",
  "PFE",
  "PINC",
  "PL",
  "PLAB",
  "PLTR",
  "PLUG",
  "PODD",
  "POET",
  "POWI",
  "PRAX",
  "PRLB",
  "PRME",
  "PSTG",
  "PTC",
  "PYPL",
  "QBTS",
  "QCOM",
  "QDEL",
  "QGEN",
  "QLYS",
  "QRVO",
  "QS",
  "QSI",
  "QTRX",
  "QUIK",
  "QURE",
  "RBLX",
  "RCUS",
  "RDW",
  "REGN",
  "REPL",
  "RGEN",
  "RGNX",
  "RGTI",
  "RIOT",
  "RIVN",
  "RKLB",
  "RMBS",
  "RMD",
  "ROK",
  "RPTX",
  "RTX",
  "RUN",
  "RVMD",
  "RVTY",
  "RXRX",
  "S",
  "SANA",
  "SANM",
  "SATS",
  "SATL",
  "SDGR",
  "SEDG",
  "SHLS",
  "SHOP",
  "SILC",
  "SITM",
  "SLAB",
  "SLDP",
  "SMCI",
  "SMG",
  "SMR",
  "SMTC",
  "SNOW",
  "SNPS",
  "SNY",
  "SOUN",
  "SPCE",
  "SPIR",
  "SPSC",
  "SPWR",
  "SRPT",
  "SSYS",
  "STAA",
  "STEM",
  "STM",
  "STVN",
  "STX",
  "SWKS",
  "SYK",
  "SYNA",
  "TARS",
  "TCMD",
  "TDG",
  "TEAM",
  "TECH",
  "TEL",
  "TEM",
  "TENB",
  "TER",
  "TEVA",
  "TGTX",
  "TM",
  "TMDX",
  "TMO",
  "TNDM",
  "TOST",
  "TRMB",
  "TSEM",
  "TSLA",
  "TSM",
  "TT",
  "TTWO",
  "TWST",
  "TXG",
  "TXN",
  "TXT",
  "TYRA",
  "U",
  "UBER",
  "UCTT",
  "UI",
  "UMC",
  "UNH",
  "UTHR",
  "VC",
  "VCYT",
  "VECO",
  "VEEV",
  "VIR",
  "VKTX",
  "VRNS",
  "VRT",
  "VRTX",
  "VSAT",
  "VSH",
  "VUZI",
  "VYGR",
  "WAT",
  "WDAY",
  "WDC",
  "WOLF",
  "WST",
  "XENE",
  "XMTR",
  "XOMA",
  "XPEV",
  "XYL",
  "ZBRA",
  "ZM",
  "ZNTL",
  "ZS",
  "ZWS"
]

thresholds:
  min_mos: 0.10

caps:
  max_growth_pe: 50
  min_growth_pe: 5

schedule:
  interval_sec: 60

logging:
  level: INFO

outputs:
  json_path: "out/results.json"   # file we’ll write each run
  include_per_strategy: true      # include strategy breakdown in the JSON
